### PR TITLE
fix(TESB-28966): MQTT: consume messages published before client start…

### PR DESCRIPTION
**Pull request by vdrokov**
…s up

### CODE REVIEW

**Comment by xldai** [comment]
As I see from the camel sources, this line "connect()" is added for fixing the https://issues.apache.org/jira/browse/CAMEL-13014 , camel mqtt crash using high volume traffic issue.
Yes, removal of this line we can fix the TESB-28966.
Just how can we sure the CAMEL-13014 is broken again?

**Comment by vdrokov** [comment]
I saw this bug reproduce even with the fix provided, so I assumed I would create this PR anyway.

**Comment by vdrokov** [comment]
I saw the bug in the ActiveMQ console while testing why the messages were dropped, and the library was not fixed with my commit during that time.

**Comment by xldai** [comment]
Okay, in this case, we can approve this PR
(TESB-28966 is fixed only on Talend side, but not Camel side, not an official fix or backport from Camel)

**Pull request merged**
